#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'

require 'rubygems'
require 'bundler'

ENV['RACK_ENV'] ||= 'development'
config_env = ENV['RACK_ENV']

bundler_env = ENV['BUNDLER_ENV'] || config_env
Bundler.require(:default, bundler_env)

# require 'pry'
# require 'gmail_xoauth'
require 'net/imap'
# require 'mail'
require_relative 'lib/core_ext'
require_relative 'lib/connection'
require_relative 'lib/cleanbox'
require_relative 'lib/folder_checker'
require_relative 'lib/message'
require_relative 'lib/microsoft_365_application_token'

require 'logger'

options = {
  host: 'outlook.office365.com',
  username: 'simon@sensadrome.com',
  clean_folders: %w[Panto Friends Family],
  whitelisted_domains: %w[filmfinances.co.uk datanauts.co.uk],
  list_domains: %w[facebookmail.com ebay.co.uk],
  list_folders: ['Admin', 'Amazon', 'Lists', 'Interests', 'School',
                 'Shopping', 'Apple', 'Ebay', 'TV and Film', 'Work', 'Misc'],
  domain_map: {
    'facebookmail.com' => 'Facebook',
    'developers.facebook.com' => 'Facebook',
    'ebay.co.uk' => 'Ebay',
    'apple.com' => 'Apple'
  },
  pretend: false,
  # password: ENV['IMAP_PASSWORD'],
  sent_folder: 'Sent Messages',
  move_read: false,
  client_id: ENV['CLIENT_ID'],
  client_secret: ENV['CLIENT_SECRET'],
  tenant_id: ENV['TENANT_ID']
}

action = 'clean!'

# rubocop:disable Metrics/BlockLength
parsed_options = OptionParser.new do |opts|
  opts.banner = 'Usage: cleanbox [options]'

  opts.on('-v', '--verbose', 'Run verbosely') do |v|
    options[:verbose] = v
    options[:level] = 'debug'
  end

  opts.on('-h', '--help', 'Prints this help') do
    puts opts
    exit
  end

  opts.on('-n', '--pretend', 'Only show what would happen') do
    options[:pretend] = true
  end

  loglevel_help = 'log level, should be one of debug, info, warn, error'
  opts.on('-L', '--level loglevel', loglevel_help) do |value|
    options[:level] = value
  end

  host_help = "Set the IMAP hostname (default '#{options[:host]}'"
  opts.on('-H', '--host HOST', host_help) do |val|
    options[:host] = val
  end

  opts.on('-u', '--user', 'Set IMAP username') do |val|
    options[:username] = val
  end

  # opts.on('-p', '--password PASSWORD', 'Set IMAP password') do |val|
  #   options[:password] = val
  # end

  opts.on('-C', '--client_id CLIENT_ID', 'Set client id for ouath2 token') do |val|
    options[:client_id] = val
  end

  opts.on('-S', '--client_secret SECRET', 'Set client secret for ouath2 token') do |val|
    options[:client_secret] = val
  end

  opts.on('-T', '--tenant_id TENANT_ID', 'Set tenant id for ouath2 token') do |val|
    options[:tenant_id] = val
  end

  logfile_help = 'Specify log file (defaults to STDOUT)'
  opts.on('-l', '--log-file LOGFILE', logfile_help) do |val|
    options[:log_file] = val
  end

  since_help = 'Only apply to messages since <parseable date>'
  opts.on('-s', '--since DATE', since_help) do |val|
    options[:since] = val
  end

  valid_from_help = 'Use addresses found since this date (default 1 year ago)'
  opts.on('-f', '--valid-from DATE', valid_from_help) do |val|
    options[:valid_from] = val
  end
end
# rubocop:enable Metrics/BlockLength

parsed_options.parse!
# Net::IMAP.debug = true

client_id = options.delete(:client_id)
client_secret = options.delete(:client_secret)
tenant_id = options.delete(:tenant_id)

token_request = Microsoft365ApplicationToken.new(client_id, client_secret, tenant_id)
imap = Net::IMAP.new(options.delete(:host), ssl: true)
imap.authenticate('XOAUTH2', options.delete(:username), token_request.token)

# imap.authenticate 'PLAIN', options.delete(:username), options.delete(:password)
# imap.send(:send_command, 'GETMETADATA', 'Deleted Messages', '/private/specialuse')

action = 'show_lists!' if ARGV.last == 'list'
action = 'file_messages!' if %w[file filing].include?(ARGV.last)
# puts "Action: #{action}"
# puts "Args: #{ARGV.inspect}"

Cleanbox.new(imap, options).send(action)
