#!/usr/bin/env ruby
# frozen_string_literal: true

# Suppress pry-byebug deprecation warning
$VERBOSE = nil

require 'optparse'
require 'yaml'

require 'rubygems'
require 'bundler'

ENV['RACK_ENV'] ||= 'development'
config_env = ENV.fetch('RACK_ENV', nil)

bundler_env = ENV['BUNDLER_ENV'] || config_env
Bundler.require(:default, bundler_env)

# require 'pry'
# require 'gmail_xoauth'
require 'net/imap'
# require 'mail'
require_relative 'lib/core_ext'
require_relative 'lib/connection'
require_relative 'lib/cleanbox'
require_relative 'lib/cleanbox_folder'
require_relative 'lib/folder_checker'
require_relative 'lib/message'
require_relative 'lib/microsoft_365_application_token'

# Load the new CLI components
require_relative 'lib/cli/cleanbox_cli'

require 'logger'

# Run the CLI application
CLI::CleanboxCLI.new.run
