#!/usr/bin/ruby

# frozen_string_literal: true

oldrev, newrev = ARGV

require 'English'

def run(cmd)
  exit($CHILD_STATUS.to_i) unless system "umask 002 && #{cmd}"
end

def run_dont_care(cmd)
  system "umask 002 && #{cmd}"
end

run "podman build -t cleanbox:latest ."
